export const FUNDRAISER_EDITED = 'FUNDRAISER_EDITED';
export const FUNDRAISER_CREATED = 'FUNDRAISER_CREATED';
export const FUNDRAISER_FETCH = 'FUNDRAISER_FETCHED';
export const FUNDRAISER_DELETED = 'FUNDRAISER_DELETED';
